#!/bin/bash

if [[ $# -eq 0 ]]; then
	echo "Usage: hd_stream IP-ADDRESS [PORT(default:5000)]" >&2
	exit 1;
fi

if [[ $# -eq 1 ]];then
	IP=$1
	PORT=5000
fi

if [[ $# -eq 2 ]];then
	IP=$1
	PORT=$2
fi

raspivid -n -fps 25 -w 1280 -h 720 -fl -t 0 -o - | nc ${IP} ${PORT}
